export const CREATE_BRAND = 'CREATE_BRAND';
export const CREATE_BRAND_ERROR = 'CREATE_BRAND_ERROR';
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const CLEAR_BRAND = 'CLEAR_BRAND';

export const CREATE_PRODUCT_TYPE = 'CREATE_PRODUCT_TYPE';
export const CREATE_PRODUCT_TYPE_ERROR = 'CREATE_PRODUCT_TYPE_ERROR';
export const CREATE_PRODUCT_TYPE_SUCCESS = 'CREATE_PRODUCT_TYPE_SUCCESS';
export const CLEAR_PRODUCT_TYPE = 'CLEAR_PRODUCT_TYPE';

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

